# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake Build

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug]
        config:
        - {name: 'Linux (latest)', os: ubuntu-latest, toolchain: '', packname: linux}

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodues: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev libpulse-dev libopengl-dev libxext-dev

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DSYSTEM_SDL=OFF

    - name: Build
      run: |
        make

    - name: Package
      run: |
        PACKAGE_NAME=unscope_${{ matrix.config.packname }}.zip
        mkdir unscope
        mv ./unscope ./unscope/unscope
        cp ../LICENSE ./unscope/LICENSE
        cp ../README.md ./unscope/README.md
        cp ../submodules/SDL/LICENSE.txt ./unscope/SDL_LICENSE.txt
        zip -r ${PACKAGE_NAME} ./unscope
        
        
    - name: Upload
      uses: actions/upload-artifact@v4.6.2
      with:
        path: unscope_*.zip
        
