name: CMake Build

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug]
        config:
        - {name: 'Linux (latest)', os: ubuntu-latest, toolchain: '', packname: linux}

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev libpulse-dev libgl-dev libopengl-dev libxext-dev

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DSYSTEM_SDL=OFF

    - name: Build
      run: |
        cd build
        cmake --build .

    - name: Package
      run: |
        PACKAGE_NAME=unscope_${{ matrix.config.packname }}.zip
        mkdir unscope
        mv build/unscope ./unscope/unscope
        cp ./LICENSE ./unscope/LICENSE
        cp ./README.md ./unscope/README.md
        cp submodules/SDL/LICENSE.txt ./unscope/SDL_LICENSE.txt
        zip -r ${PACKAGE_NAME} ./unscope
        
        
    - name: Upload
      uses: actions/upload-artifact@v4.6.2
      with:
        name: unscope_artifact
        path: unscope_*.zip
        
